mss_name,CRADA MSS
mss_doc_version,1.00.00
mss_html_version,crada

arrangement_frame,mss/base_crada/htm/arrangement_frame.htm
arrangement_buoyancy,mss/base_crada/htm/arrangement_buoyancy.htm
arrangement_power,mss/base_crada/htm/arrangement_power.htm
arrangement_communications,mss/base_crada/htm/arrangement_communications.htm
arrangement_ahrsd,mss/base_crada/htm/arrangement_ahrsd.htm
arrangement_thrusters,mss/base_crada/htm/arrangement_thrusters.htm
arrangement_cameras,mss/base_crada/htm/arrangement_cameras.htm
arrangement_lights,mss/base_crada/htm/arrangement_lights.htm
